JahanAraShop/Areas/Admin/Models/NewsViewModel.cs
using JahanAraShop.Domain.DomainModel;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;

namespace JahanAraShop.Areas.Admin.Models
{
    public class NewsViewModel
    {
        public List<tblSiteInformation> ListSiteInformations { get; set; }
        public tblSiteInformation SiteInformation { get; set; }
        
    }

}

JahanAraShop/Areas/Admin/Controllers/PanelController.cs
using JahanAraShop.Areas.Admin.Models;
using JahanAraShop.Data.Context;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JahanAraShop.Services;
using JahanAraShop.Domain.Constants;
using System.Text;
using JahanAraShop.Domain.DomainModel;

namespace JahanAraShop.Areas.Admin.Controllers
{
    public partial class PanelController : Controller
    {

        
        // GET: Admin/Panel
        public virtual ActionResult Index()
        {
            return View();
        }


        public virtual ActionResult SlidShow()
        {
            using (var db = new DataBaseContext())
            {
                SlideShowViewModel model = new SlideShowViewModel();
                if (TempData["message"] != null)
                {

                    TempData["message"] = TempData["message"];

                }
                else
                {
                    TempData["message"] = null;
                }
                model.ListSlideShow = db.TblSiteSlideShow.OrderBy(m => m.Priority).ToList();
                return View(model);
            }

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public virtual ActionResult SlideShow(SlideShowViewModel model, HttpPostedFileBase imgFa)
        {
            var allowedExtensions = new[]
                {
                  ".Jpg", ".png", ".jpg", "jpeg",".bmp"
                };
            if (imgFa != null)
            {


                var fileNameIMG = Path.GetFileName(imgFa.FileName); //getting only file name(ex-ganesh.jpg)  
                var extIMG = Path.GetExtension(imgFa.FileName); //getting the extension(ex-.jpg)  
                if (allowedExtensions.Contains(extIMG)) //check what type of extension  
                {
                    using (System.Drawing.Image image = System.Drawing.Image.FromStream(imgFa.InputStream, true, true))
                    {
                        if (image.Width == 1920 && image.Height == 995)
                        {
                            string finalFileNameIMG = Guid.NewGuid().ToString() + extIMG;
                            var pathIMG = Path.Combine(Server.MapPath("/Content/images/Slider"), finalFileNameIMG);


                            imgFa.SaveAs(pathIMG);
                            model.SlideShow.Picture = finalFileNameIMG;

                            using (var db = new DataBaseContext())
                            {
                                db.TblSiteSlideShow.Add(model.SlideShow);
                                db.SaveChanges();
                            }
                        }
                        else
                        {
                            TempData["message"] = "لطفا تصویر را در اندازه 995*1920 و حجم کمتر از 100 کیلوبایت ارسال فرمایید";
                            return RedirectToAction(MVC.Admin.Panel.SlidShow());
                        }
                    }

                }
                else
                {
                    TempData["message"] = "لطفا تصویر را در قالب عکس ارسال فرمایید";
                    return RedirectToAction(MVC.Admin.Panel.SlidShow());
                }
            }
            TempData["message"] = " با موفقیت اپلود شد";
            return RedirectToAction(MVC.Admin.Panel.SlidShow());

        }

        public virtual ActionResult News()
        {
            using (var db = new DataBaseContext())
            {
                NewsViewModel model = new NewsViewModel();
                model.ListSiteInformations = db.tblSiteInformations.ToList();

                return View(model);
            }


        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public virtual ActionResult SaveNews(NewsViewModel model, HttpPostedFileBase imgFa)
        {
            using (var db = new DataBaseContext())
            {


                var allowedExtensions = new[]
                {
                  ".Jpg", ".png", ".jpg", "jpeg",".bmp"
                };
                if (imgFa != null)
                {


                    var fileNameIMG = Path.GetFileName(imgFa.FileName); //getting only file name(ex-ganesh.jpg)  
                    var extIMG = Path.GetExtension(imgFa.FileName); //getting the extension(ex-.jpg)  
                    if (allowedExtensions.Contains(extIMG)) //check what type of extension  
                    {
                        using (System.Drawing.Image image = System.Drawing.Image.FromStream(imgFa.InputStream, true, true))
                        {
                            if (image.Width <= 345 && image.Height <= 211)
                            {
                                string finalFileNameIMG = Guid.NewGuid().ToString() + extIMG;
                                var pathIMG = Path.Combine(Server.MapPath("/Content/images/News"), finalFileNameIMG);


                                imgFa.SaveAs(pathIMG);
                                model.SiteInformation.SmallPicture = finalFileNameIMG;
                                model.SiteInformation.LargePicture = finalFileNameIMG;
                                model.SiteInformation.IdtblInformationType = 1;
                                model.SiteInformation.CreateDate = Utilities.ParsToChrisDate(model.SiteInformation.FarsiCreateDate);
                                db.tblSiteInformations.Add(model.SiteInformation);
                                db.SaveChanges();

                            }
                            else
                            {
                                TempData["message"] = "لطفا تصویر را در اندازه 995*1920 و حجم کمتر از 100 کیلوبایت ارسال فرمایید";
                                return RedirectToAction(MVC.Admin.Panel.News());
                            }
                        }

                    }
                    else
                    {
                        TempData["message"] = "لطفا تصویر را در قالب عکس ارسال فرمایید";
                        return RedirectToAction(MVC.Admin.Panel.News());
                    }
                }
                return RedirectToAction(MVC.Admin.Panel.News());
            }


        }


        public virtual JsonResult DeleteNews(int Id)
        {
            using (var db = new DataBaseContext())
            {
                var news = db.tblSiteInformations.Where(x => x.IdtblInformation == Id).SingleOrDefault();
                if (news != null)
                {
                    db.tblSiteInformations.Remove(news);
                    db.SaveChanges();
                    return Json(new { result = true });


                }

                else
                {
                    return Json(new { result = false });

                }
            }


        }

        public virtual ActionResult InvoiceList()
        {
            return View();

        }

        [HttpPost]
        public virtual ActionResult GetInvoiceReport(InvoiceReportModel model)
        {
            using (var db = new DataBaseContext())
            {
                if (model.CustomerPhone != null)
                {
                    var query = (from invoice in db.tblSaleInvoices
                                 join org in db.tblOrganizations on invoice.CustomerId equals org.ID
                                 where invoice.FarsiCreateDate.CompareTo(model.FromDate) >= 0 && invoice.FarsiCreateDate.CompareTo(model.ToDate) <= 0
                                 && org.CellPhone == model.CustomerPhone
                                 select new
                                 {
                                     invoice.Id,
                                     invoice.FarsiCreateDate,
                                     invoice.TotalValue,
                                     invoice.Transfer,
                                     organame = org.FirstName + " " + org.Name,
                                     invoice.ManualCode,
                                     invoice.SuchargeValue


                                 }).ToList();


                    return Json(query, JsonRequestBehavior.AllowGet);
                }
                else
                {


                    var query = (from invoice in db.tblSaleInvoices
                                 join org in db.tblOrganizations on invoice.CustomerId equals org.ID
                                 where invoice.FarsiCreateDate.CompareTo(model.FromDate) >= 0 && invoice.FarsiCreateDate.CompareTo(model.ToDate) <= 0
                                
                                 select new
                                 {
                                     invoice.Id,
                                     invoice.FarsiCreateDate,
                                     invoice.TotalValue,
                                     invoice.Transfer,
                                     organame = org.FirstName + " " + org.Name,
                                     invoice.ManualCode,
                                     invoice.SuchargeValue


                                 }).ToList();


                    return Json(query, JsonRequestBehavior.AllowGet);

                }
            }

        }

        public virtual ActionResult CreateDiscountcode()            
        {

            using (var db = new DataBaseContext())
            {
                DicountCodeViewModel model = new DicountCodeViewModel();
                var customer = db.tblOrganizations.ToDictionary(x => x.ID, x =>x.FirstName+' '+ x.Name+'-'+x.CellPhone);
                SelectListItem[] tempList = new SelectListItem[customer.Count];
                int i = 0;
                foreach (var item in customer)
                {
                    tempList[i] = new SelectListItem
                    {
                        Value = item.Key.ToString(),
                        Text = item.Value
                    };
                    i++;
                }
                

JahanAraShop/Controllers/NewsController.cs
using JahanAraShop.Data.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JahanAraShop.Controllers
{
    public partial class NewsController : Controller
    {
        // GET: News
        public virtual ActionResult Index()
        {

            using (var db = new DataBaseContext())
            {


                var list = db.tblSiteInformations.OrderByDescending(x => x.FarsiCreateDate).ToList();
                return View(list);
            }

        }


        public virtual ActionResult GetData(int pageIndex, int pageSize)
        {
            System.Threading.Thread.Sleep(4000);
            using (var db = new DataBaseContext())
            {
                var query = (from c in db.tblSiteInformations
                             orderby c.IdtblInformation ascending
                             select c)
                             .Skip((pageIndex) * pageSize)
                             .Take(pageSize);
                return Json(query.ToList(), JsonRequestBehavior.AllowGet);
            }
        }
    }
}

JahanAraShop/Areas/Admin/Views/Panel/News.cshtml
@model JahanAraShop.Areas.Admin.Models.NewsViewModel
@using JahanAraShop.Services
@{
    ViewBag.Title = "News";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/css/PersianDatePicker.min.css" rel="stylesheet" />
<section id="main-content" class=" ">
    <section class="wrapper main-wrapper row" style=''>

        <div class='col-xs-12'>
            <div class="page-title">

                <div class="pull-right">
                    <!-- PAGE HEADING TAG - START --><h1 class="title">File Uploader - Custom</h1><!-- PAGE HEADING TAG - END -->
                </div>

                <div class="pull-left hidden-xs">
                    <ol class="breadcrumb">
                        <li>
                            <a href="index.html"><i class="fa fa-home"></i>Home</a>
                        </li>
                        <li>
                            <a href="form-fileupload-dropzone.html">File Uploader</a>
                        </li>
                        <li class="active">
                            <strong>Custom Uploader</strong>
                        </li>
                    </ol>
                </div>

            </div>
        </div>
        <div class="clearfix"></div>
        <!-- MAIN CONTENT AREA STARTS -->
        <div class="col-lg-12">
            <section class="box ">
                <header class="panel_header">
                    <h2 class="title pull-right">ثبت اخبار</h2>
                    <div class="actions panel_actions pull-left">
                        <a class="box_toggle fa fa-chevron-down"></a>
                        <a class="box_setting fa fa-cog" data-toggle="modal" href="#section-settings"></a>
                        <a class="box_close fa fa-times"></a>
                    </div>
                </header>
                <div class="content-body dr ">
                    @using (Html.BeginForm("SaveNews", "Panel", FormMethod.Post, new { id = "Details", @class = "checkout sec-mar", enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary("", new { @class = "blockdisp text-danger" })

                        <div class="row ">

                            <div class="alert alert-success alert-dismissible fade in" hidden id="alerts">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                                @TempData["message"]
                            </div>

                            <div class="col-xs-12">
                                <div class="custom-dropzone row">
                                    <div class="col-sm-8 ">
                                        <input type="file" id="fileUp" accept=".Jpg,.png,.jpg,.jpeg,.bmp" title="search image" name="imgFa" dir="ltr" />
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-6  fl">
                                @{string a = Utilities.FarsiDateTimeNow();}

                                @Html.LabelFor(m => m.SiteInformation.FarsiCreateDate)
                                @Html.EditorFor(m => m.SiteInformation.FarsiCreateDate, new { htmlAttributes = new { id = "FarsiCreateDate", @class = "form-control", placeholder = "----/--/--", maxlength = "10", onclick = "PersianDatePicker.Show(this,'" + a + "')" } })

                                @Html.LabelFor(m => m.SiteInformation.FarsiTitle)
                                <label><span>*</span></label>
                                @Html.TextBoxFor(m => m.SiteInformation.FarsiTitle, new { @class = "form-control" })


                                @Html.LabelFor(m => m.SiteInformation.FarsiSmallDescription)
                                <span>*</span>
                                @Html.TextBoxFor(m => m.SiteInformation.FarsiSmallDescription, new { @class = "form-control" })

                                @Html.LabelFor(m => m.SiteInformation.FarsiDescription)
                                <span>*</span>
                                @Html.TextAreaFor(m => m.SiteInformation.FarsiDescription, new { @class = "form-control" })

                                <br />
                                <div class="form-group">
                                    <button type="submit" class="btn btn-purple  pull-left">ثبت</button>
                                </div>
                            </div>
                        </div>
                                    }
                </div>
            </section>
                <section class="box" style=''>
                    <div class="clearfix"></div>
                    <!-- MAIN CONTENT AREA STARTS -->
                    <div class="col-lg-12">
                        <section class="box ">
                            <header class="panel_header">
                                <h2 class="title pull-right">اخبار</h2>
                                <div class="actions panel_actions pull-left">
                                    <a class="box_toggle fa fa-chevron-down"></a>
                                    <a class="box_setting fa fa-cog" data-toggle="modal" href="#section-settings"></a>
                                    <a class="box_close fa fa-times"></a>
                                </div>
                            </header>
                            <div class="content-body">
                                <div class="row dr">
                                    <div class="col-xs-12">
                                        <!-- ********************************************** -->
                                        <table id="example" class="display table table-hover table-condensed fl">
                                            <thead>
                                                <tr>
                                                    <th>ردیف</th>
                                                    <th style="width:10%;">عکس</th>
                                                    <th>تاریخ</th>
                                                    <th>عنوان</th>
                                                    <th>حذف</th>
                                                </tr>
                                            </thead>


                                            @{var Row = 1;}
                                            <tbody>
                                                @foreach (var item in Model.ListSiteInformations)
                                                {
                                                    <tr>
                                                        <td>@Row</td>
                                                        <td>
                                                            <figure class="pdt_thumb">
                                                                <img style="max-width:100%;" src="@(JahanAraShop.Application.Resources.Paths.ImageFolder)News/@(item.SmallPicture)" alt="">
                                                            </figure>
                                                        </td>
                                                        <td style="width:10%;">@item.FarsiCreateDate</td>
                                                        <td data-id="@item.IdtblInformation">@item.FarsiSmallDescription</td>
                                                        <td class="itemDesc"><span class="fa fa-remove removeItem"></span></td>
                                                    </tr>
                                                    Row++;

                                                }

                                            </tbody>
                                        </table>

                                        <!-- MAIN CONTENT AREA ENDS -->
                                    </div>
                                </div>
                            </div>
                        </section>
                   </div>
                </section>
        </div>

        <div class="dir" id="dialog"></div>
        <!-- Modal -->
        <div class="modal fade" id="Added" role="dialog">
            <div class="modal-dialog">
                <!-- Modal content-->
                <div class="modal-content dir">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">اخبار</h4>
                    </div>
                    <div class="modal-body">
                        <p style="text-align:right;">با موفقیت حذف شد</p>
                    </div>
                </div>
            </div>
        </div>
        <!-- MAIN CONTENT AREA ENDS -->
    </section>
</section>



@section Scripts {
    <script src="~/Content/js/PersianDatePicker.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function () {

            jQuery(".removeItem").click(function () {
                var $this = jQuery(this)[0];
                showConfirm("این خبر حذف شود؟", function () {
                    $row = $this.closest("tr");
                    jQuery($row.closest("tr")).nextAll('tr.rowItem').each(function () {//بروز کردن شماره ردیف عناصر بعدی
                        var $radif = jQuery(this).children('.id');
                        $radif.text(parseInt($radif.text()) - 1);
                    });
                    $row.remove();//حذف آیتم

                    var $item = jQuery($this).closest('td').prev('td');
                    var Infoid = $item.data("id");
                    DeleteNews(Infoid);

                });
            });
        });

        var showConfirm = function (msg, success) {
            jQuery("#dialog").text(msg);
            jQuery("#dialog").dialog({
                title: "توجه",
                width: 500,
                modal: true,
                buttons: {
                    ok: {
                        // class: 'leftButton',
                        text: 'بله ',
                        click: function () {
                            success();
                            jQuery(this).dialog("close");
                        }
                    },
                    cancel: {//class: 'leftButton',
                        text: 'خیر',
                        click: function () {
                            jQuery(this).dialog("close");
                        }
                    }
                }
            });
        };
        var showAlert = function (msg) {
            jQuery("#dialog").text(msg);
            jQuery("#dialog").dialog({
                title: "توجه",
                width: 500,
                modal: true,
                buttons: {
                    ok: {
                        text: 'تائید ', click: function ()
                        { jQuery(this).dialog("close"); }
                    }
                }
            });
        };


        function DeleteNews(Infoid) {
            $.ajax({
                type: 'Post',
                url: '/Panel/DeleteNews/',
                data: { "Id": Infoid },
                dataType: "json",
                success: function (data) {

                    if (data.isRedirect) {

                        window.location.href = data.redirectUrl;
                    }
                    else {
                        if (data.result) {

                            $("#Added").modal();
                            $(".modal-backdrop").detach();

                        }

                    }

                },
                error: function (jqXHR, textStatus, errorThrown) {
                    alert('error: ' + textStatus + ': ' + errorThrown);
                }
            });
        }
    </script>
}

JahanAraShop/Areas/Admin/Views/Panel/SlidShow.cshtml
@model JahanAraShop.Areas.Admin.Models.SlideShowViewModel
@{
    ViewBag.Title = "SlidShow";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<section id="main-content" class=" ">
    <section class="wrapper main-wrapper row" style=''>

        <div class='col-xs-12'>
            <div class="page-title">

                <div class="pull-right">
                    <!-- PAGE HEADING TAG - START --><h1 class="title">File Uploader - Custom</h1><!-- PAGE HEADING TAG - END -->
                </div>

                <div class="pull-left hidden-xs">
                    <ol class="breadcrumb">
                        <li>
                            <a href="index.html"><i class="fa fa-home"></i>Home</a>
                        </li>
                        <li>
                            <a href="form-fileupload-dropzone.html">File Uploader</a>
                        </li>
                        <li class="active">
                            <strong>Custom Uploader</strong>
                        </li>
                    </ol>
                </div>

            </div>
        </div>
        <div class="clearfix"></div>
        <!-- MAIN CONTENT AREA STARTS -->

        <div class="col-lg-12">
            <section class="box ">
                <header class="panel_header">
                    <h2 class="title pull-right">Custom Uploader</h2>
                    <div class="actions panel_actions pull-left">
                        <a class="box_toggle fa fa-chevron-down"></a>
                        <a class="box_setting fa fa-cog" data-toggle="modal" href="#section-settings"></a>
                        <a class="box_close fa fa-times"></a>
                    </div>
                </header>
                <div class="content-body dr ">
                    @using (Html.BeginForm("SlideShow", "Panel", FormMethod.Post, new { id = "Details", @class = "checkout sec-mar", enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary("", new { @class = "blockdisp text-danger" })

                        <div class="row ">
                          
                            <div class="alert alert-success alert-dismissible fade in"  hidden id="alerts">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                                 @TempData["message"]
                            </div>
                           
                            <div class="col-xs-12">
                                <div class="custom-dropzone row">
                                    <div class="col-sm-8 ">
                                        <input type="file" id="fileUp" accept=".Jpg,.png,.jpg,.jpeg,.bmp" title="search image" name="imgFa" dir="ltr" />
                                    </div>                                
                                </div>
                            </div>

                            <div class="col-xs-6  fl">
                                @Html.LabelFor(m => m.SlideShow.FarsiTitle)
                                @Html.TextBoxFor(m => m.SlideShow.FarsiTitle, new { @class = "form-control" })
                                

                                @Html.LabelFor(m => m.SlideShow.FarsiDescription)
                                @Html.TextBoxFor(m => m.SlideShow.FarsiDescription, new { @class = "form-control" })
                                
                                <label>وضعیت نمایش</label>
                                @Html.DropDownListFor(m => m.SlideShow.IsEnabled, (IEnumerable<SelectListItem>)Model.listVisible, new { id = "Visible", @class = "name-element txt form-control", name = "fcVisible" })
                                
                                <label>اولویت</label>
                                @Html.TextBoxFor(m => m.SlideShow.Priority, new { @class = "form-control" })
                                <br />
                                <div class="form-group">

                                    <button type="submit" class="btn btn-purple  pull-left">ثبت</button>
                                </div>
                            </div>


                        </div>
                    }
                </div>


            </section>
        </div>


        <!-- MAIN CONTENT AREA ENDS -->
    </section>
</section>
<script type="text/javascript">
    jQuery(document).ready(function () {

        var success = @((TempData["message"] != null).ToString().ToLower());    
        if(success==true)
        {
            $("#alerts").show();

        }


    });

</script>